### ISSUE TITLE
provision_lab.yml fails on Mac OS

### ISSUE THREAD

**Issue by danielcayer** [f5alliances/f5_provisioner#14]
I wonder if this could be due to the fact that I'm running python version 3.7.4?  (https://github.com/f5alliances/f5_provisioner/issues/9)

cayer@FLD-VM-00028141:~/Documents/f5_provisioner/provisioner$ **_ansible-playbook provision_lab.yml -e @f5_vars.yml -vvvvv_**

_[output linesomitted for brevity]_

TASK [user_accounts : Create User Account] **********************************************************************************************************************************************
task path: /Users/cayer/Documents/f5_provisioner/provisioner/roles/user_accounts/tasks/main.yml:9
fatal: [DANTESTWORKSHOP1-student1-ansible]: FAILED! =>
  msg: 'An unhandled exception occurred while templating ''{{ admin_password | password_hash(salt=''sRvXWmR5BBwqRlih'') }}''. Error was a <class ''ansible.errors.AnsibleFilterError''>,original message: crypt.crypt not supported on Mac OS X/Darwin, install passlib python module'
fatal: [DANTESTWORKSHOP1-student1-host1]: FAILED! =>
  msg: 'An unhandled exception occurred while templating ''{{ admin_password | password_hash(salt=''sRvXWmR5BBwqRlih'') }}''. Error was a <class ''ansible.errors.AnsibleFilterError''>,original message: crypt.crypt not supported on Mac OS X/Darwin, install passlib python module'
fatal: [DANTESTWORKSHOP1-student1-host2]: FAILED! =>
  msg: 'An unhandled exception occurred while templating ''{{ admin_password | password_hash(salt=''sRvXWmR5BBwqRlih'') }}''. Error was a <class ''ansible.errors.AnsibleFilterError''>,original message: crypt.crypt not supported on Mac OS X/Darwin, install passlib python module

**_ansible --version_**
ansible 2.8.3
  config file = /Users/cayer/Documents/f5_provisioner/provisioner/ansible.cfg
  configured module search path = ['/Users/cayer/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.4 (default, Sep  7 2019, 18:27:02) [Clang 10.0.1 (clang-1001.0.46.4)]
cayer@FLD-VM-00028141:~/Documents/f5_provisioner/provisioner$

**_pip install --upgrade passlib_**
Requirement already up-to-date: passlib in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (1.7.1)
cayer@FLD-VM-00028141:~/Documents/f5_provisioner/provisioner$

**Comment by payalsin** [comment]
Not sure looked online but solution is to have the passlib installed which you do.

Can you try using a docker container which has all the pre-requisites installed for running the provisioner, that way we move away from debugging individual environments

https://github.com/f5alliances/f5_provisioner/blob/master/docker/README.md

**Comment by danielcayer** [comment]
Thanks Payal !
I missed the fact that your repo already includes a docker container for the F5 Ansible provisioner! Nice! I will give it a try later.


Sincères salutations,

Daniel Cayer
+1-613-868-1535<tel:+1-613-868-1535>  |  danielcayer@hotmail.com<mailto:danielcayer@hotmail.com>

**Comment by ericzji** [comment]
Provisioner repo has been moved to devCentral: https://github.com/f5devcentral/FAS-provisioner. For any of the issue, we will fixit in devCentral Repo. 

Please help duplicate the issue to devCentral repo. 
Thanks @danielcayer

**Comment by ericzji** [comment]
Migrated to https://github.com/f5devcentral/FAS-provisioner/issues/3
