### ISSUE TITLE
404 not found in help

### ISSUE THREAD

**Issue by pmscheffler** [f5alliances/f5_provisioner#17]
In the README there is this text:

AWS Setup
Create an Amazon AWS account.

Create an Access Key ID and Secret Access Key. Save the ID and key for later.

New to AWS and not sure what this step means? **Click here**

the address is https://github.com/f5alliances/f5_provisioner/blob/master/docs/aws-directions/AWSHELP.md

The link under "click here" is broken for me.

**Comment by jasonrahm** [comment]
same. Is that information available somewhere in a consolidated manner?

**Comment by payalsin** [comment]
Fixed.

Link to how to get the AWS Key's: https://aws.amazon.com/premiumsupport/knowledge-center/create-access-key/
