### ISSUE TITLE
Install AS3 to BIG-IP

### ISSUE THREAD

**Issue by cavalen** [f5alliances/f5_provisioner#19]
AS3 is not installed and as3 installation is not part of the scope of an Ansible class
This should be installed from the Provisioner.

**Comment by ericzji** [comment]
Provisioner repo has been moved to devCentral: https://github.com/f5devcentral/FAS-provisioner. For any of the issue, we will fixit in devCentral Repo. 

Please help duplicate the issue to devCentral repo. 
Thanks @cavalen

**Comment by ericzji** [comment]
We moved AS3 install out of Provisioner, and created a use case for it: 
https://github.com/f5devcentral/FAS-ansible-use-cases/tree/master/05-install-as3
