### ISSUE TITLE
AMI which need be subscribed is wrong

### ISSUE THREAD

**Issue by boroboromy** [f5alliances/f5_provisioner#20]
At the step 6 of AWS setup, "Make sure you have subscribed to the right marketplace AMI (Amazon Machine Image)", the link Click Here direct to F5 BIG-IP Virtual Edition - GOOD (PAYG, 25Mbps)， while it is "name: "F5 Networks Prelicensed Hourly BIGIP-13.1.0.7-0.0.1 - Best 25MBPS *" " in /root/f5_provisioner/provisioner/roles/manage_ec2_instances/defaults. It misleads process

**Comment by ericzji** [comment]
migrated to https://github.com/f5devcentral/FAS-provisioner/issues/6
we moved the repo there, and along with issues.
