### ISSUE TITLE
Linux AMI harcoded

### ISSUE THREAD

**Issue by codygreen** [f5alliances/f5_provisioner#8]
Please abstract the linux AMI information to a variable so customers that only have access to private market places, such as the F5 UDF environment, can still deploy the f5 provisioner.

Another option would be to search for the latest version of the AMI versus requiring a hardcoded version.

Related to issue #7

**Comment by payalsin** [comment]
Will add provision for Linux as well as F5 AMI

**Comment by ericzji** [comment]
Provisioner repo has been moved to devCentral: https://github.com/f5devcentral/FAS-provisioner. For any of the issue, we will fixit in devCentral Repo. 

Please help duplicate the issue to devCentral repo. 
Thanks @codygreen

**Comment by ericzji** [comment]
migrated to https://github.com/f5devcentral/FAS-provisioner/issues/2
