### ISSUE TITLE
Python3 Support

### ISSUE THREAD

**Issue by codygreen** [f5alliances/f5_provisioner#9]
I can only successfully deployment the provisioner via Python 2.7.  When I attempt to do this with Python3 the following task always fails:
TASK [connectivity_test : Wait 400 seconds (using wait_for_connection)]

**Comment by payalsin** [comment]
Yes this has only been tested with Python 2.7. We will add in documentation to use Python 2.7 and make sure to test with Python 3.0 moving forward

**Comment by ericzji** [comment]
I tried Python3 in my environment, and it worked fine. Can you help do a couple of things: 1) re-run it as per the instruction; 2) if it still fails, please enable verbose mode -vvvv. thanks

**Comment by ericzji** [comment]
Provisioner repo has been moved to devCentral: https://github.com/f5devcentral/FAS-provisioner. For any of the issue, we will fixit in devCentral Repo. 

Please help duplicate the issue to devCentral repo. 
Thanks @codygreen

**Comment by ericzji** [comment]
Migrated to https://github.com/f5devcentral/FAS-provisioner/issues/3
